{
 "title": "Waterstream Debug",
 "tags": [
  "mqtt",
  "waterstream"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_received[1m]))",
     "legendFormat": "received rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_publish_received)",
     "legendFormat": "received total count"
    },
    {
     "expr": "sum(rate(mqtt_proxy_published_to_kafka[1m]))",
     "legendFormat": "kafka publish rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_published_to_kafka)",
     "legendFormat": "kafka total publish count"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_sent[1m]))",
     "legendFormat": "rate, msg/sec"
    },
    { "expr": "sum(mqtt_proxy_publish_sent)", "legendFormat": "total count" }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_clients_current)",
     "legendFormat": "connected clients"
    }
   ]
  },
  {
   "title": "Client connections details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_connect_received)",
     "legendFormat": "CONNECT received"
    },
    { "expr": "sum(mqtt_proxy_accept_sent)", "legendFormat": "ACCEPT sent" },
    {
     "expr": "sum(mqtt_proxy_inactive_clients_disconnected)",
     "legendFormat": "Inactive clients disconnected"
    },
    {
     "expr": "sum(mqtt_proxy_connections_closed)",
     "legendFormat": "connections closed"
    },
    {
     "expr": "sum(mqtt_proxy_disconnect_received)",
     "legendFormat": "DISCONNECT received"
    },
    {
     "expr": "sum(mqtt_proxy_connect_rejected)",
     "legendFormat": "connections rejected"
    },
    {
     "expr": "sum(mqtt_proxy_overloaded_clients_disconnected)",
     "legendFormat": "overloaded disconnected"
    }
   ]
  },
  {
   "title": "MQTTD Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"mqttd-monitoring\", area=\"heap\"}",
     "legendFormat": "Heap usage, bytes ({{instance}})"
    },
    {
     "expr": "jvm_memory_bytes_max{service=\"mqttd-monitoring\", area=\"heap\"}",
     "legendFormat": "Heap max size, bytes ({{instance}})"
    }
   ]
  },
  {
   "title": "MQTTD GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_sum{service=\"mqttd-monitoring\"})",
     "legendFormat": "GC Time"
    },
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{service=\"mqttd-monitoring\"}[1m]))",
     "legendFormat": "GC Time Fraction"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{service=\"mqttd-monitoring\"}",
     "legendFormat": "threads({{state}})"
    }
   ]
  },
  {
   "title": "MQTT Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_sessions_fresh_start_count)",
     "legendFormat": "Fresh sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_loaded_count)",
     "legendFormat": "Loaded sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_not_found_count)",
     "legendFormat": "Not found sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_load_duration)",
     "legendFormat": "Sessions load duration, ms"
    }
   ]
  },
  {
   "title": "Clients by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_proxy_clients_current", "legendFormat": "Clients on {{instance}}" }
   ]
  }
 ]
}