#!/bin/sh

set -e
SCRIPT_DIR=`realpath $(dirname "$0")`

#. $SCRIPT_DIR/version.sh
. $SCRIPT_DIR/config.sh

CONTAINER_NAME=waterstream-kafka
echo Starting $CONTAINER_NAME
IMAGE_NAME=simplematter/waterstream-kafka:$WATERSTREAM_VERSION

#interactive
#INTERACTIVE=-it
#non-interactive
INTERACTIVITY=-d

#No cleanup
CLEANUP=""
#Remove container automatically when completed
#CLEANUP="--rm"

docker run $INTERACTIVITY $CLEANUP \
     -e KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS \
     -e KAFKA_SASL_JAAS_CONFIG="$KAFKA_SASL_JAAS_CONFIG" \
     -e KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=$KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
     -e KAFKA_SASL_MECHANISM=$KAFKA_SASL_MECHANISM \
     -e KAFKA_SECURITY_PROTOCOL=$KAFKA_SECURITY_PROTOCOL \
     -e KAFKA_REQUEST_TIMEOUT_MS=$KAFKA_REQUEST_TIMEOUT_MS \
     -e KAFKA_RETRY_BACKOFF_MS=$KAFKA_RETRY_BACKOFF_MS \
     -e KAFKA_PRODUCER_LINGER_MS=$KAFKA_PRODUCER_LINGER_MS\
     -e KAFKA_BATCH_SIZE=$KAFKA_BATCH_SIZE\
     -e KAFKA_COMPRESSION_TYPE=$KAFKA_COMPRESSION_TYPE\
     -e KAFKA_FETCH_MIN_BYTES=$KAFKA_FETCH_MIN_BYTES \
     -e COROUTINES_THREADS=$COROUTINES_THREADS \
     -e KAFKA_TRANSACTIONAL_ID=$KAFKA_TRANSACTIONAL_ID \
     -e SESSION_TOPIC=$SESSION_TOPIC \
     -e RETAINED_MESSAGES_TOPIC=$RETAINED_MESSAGES_TOPIC \
     -e CONNECTION_TOPIC=$CONNECTION_TOPIC \
     -e KAFKA_MESSAGES_DEFAULT_TOPIC=$KAFKA_MESSAGES_DEFAULT_TOPIC \
     -e KAFKA_MESSAGES_TOPICS_PATTERNS=$KAFKA_MESSAGES_TOPICS_PATTERNS \
     -e KAFKA_STREAMS_APPLICATION_NAME=$KAFKA_STREAMS_APPLICATION_NAME \
     -e KAFKA_STREAMS_STATE_DIRECTORY=$KAFKA_STREAMS_STATE_DIRECTORY \
     -e KAFKA_RESET_STREAMS_ON_START=$KAFKA_RESET_STREAMS_ON_START \
     -e KAFKA_RESET_STREAMS_ON_EXIT=$KAFKA_RESET_STREAMS_ON_EXIT \
     -e CENTRALIZED_CONSUMER_LISTENER_QUEUE=$CENTRALIZED_CONSUMER_LISTENER_QUEUE \
     -e KAFKA_STREAMS_REPLICATION_FACTOR=$KAFKA_STREAMS_REPLICATION_FACTOR \
     -e KAFKA_STREAMS_APP_SERVER_HOST=$KAFKA_STREAMS_APP_SERVER_HOST \
     -e KAFKA_STREAMS_APP_SERVER_PORT=$KAFKA_STREAMS_APP_SERVER_PORT \
     -e KAFKA_STREAMS_APP_SERVER_SHARED_TOKEN=$KAFKA_STREAMS_APP_SERVER_SHARED_TOKEN \
     -e KAFKA_STREAMS_PROPAGATION_UNDECISIVE_TIMEOUT_MS=5000 \
     -e MQTT_BLOCKING_THREAD_POOL_SIZE=$MQTT_BLOCKING_THREAD_POOL_SIZE \
     -e MAX_QUEUED_INCOMMING_MESSAGES=$MAX_QUEUED_INCOMMING_MESSAGES \
     -e MQTT_MAX_IN_FLIGHT_MESSAGES=$MQTT_MAX_IN_FLIGHT_MESSAGES \
     -e MONITORING_INCLUDE_JAVA_METRICS=$MONITORING_INCLUDE_JAVA_METRICS \
     -e MONITORING_EXTENDED_METRICS=$MONITORING_EXTENDED_METRICS \
     -e MQTT_MAX_MESSAGE_SIZE=$MQTT_MAX_MESSAGE_SIZE \
     -e WATERSTREAM_JAVA_OPTS="-XX:InitialRAMPercentage=$WATERSTREAM_RAM_PERCENTAGE -XX:MaxRAMPercentage=$WATERSTREAM_RAM_PERCENTAGE" \
     -v $SCRIPT_DIR/waterstream.license:/etc/waterstream.license:ro \
     -p $KAFKA_STREAMS_APP_SERVER_PORT:$KAFKA_STREAMS_APP_SERVER_PORT \
     -p $MQTT_PORT:1883 \
     -p $MONITORING_PORT:1884 \
     --name $CONTAINER_NAME $IMAGE_NAME



