#!/bin/sh

set -e
SCRIPT_DIR=`realpath $(dirname "$0")`

#. $SCRIPT_DIR/version.sh
. $SCRIPT_DIR/config.sh

CONTAINER_NAME=waterstream-kafka
echo Starting $CONTAINER_NAME
IMAGE_NAME=simplematter/waterstream-kafka-minified:$MQTTD_VERSION

#interactive
#INTERACTIVE=-it
#non-interactive
INTERACTIVITY=-d

#No cleanup
CLEANUP=""
#Remove container automatically when completed
#CLEANUP="--rm"

docker run $INTERACTIVITY $CLEANUP \
     -e KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS \
     -e KAFKA_SASL_JAAS_CONFIG="$KAFKA_SASL_JAAS_CONFIG" \
     -e KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=$KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
     -e KAFKA_SASL_MECHANISM=$KAFKA_SASL_MECHANISM \
     -e KAFKA_SECURITY_PROTOCOL=$KAFKA_SECURITY_PROTOCOL \
     -e KAFKA_REQUEST_TIMEOUT_MS=$KAFKA_REQUEST_TIMEOUT_MS \
     -e KAFKA_RETRY_BACKOFF_MS=$KAFKA_RETRY_BACKOFF_MS \
     -e COROUTINES_THREADS=$COROUTINES_THREADS \
     -e KAFKA_TRANSACTIONAL_ID=$KAFKA_TRANSACTIONAL_ID \
     -e SESSION_TOPIC=$SESSION_TOPIC \
     -e RETAINED_MESSAGES_TOPIC=$RETAINED_MESSAGES_TOPIC \
     -e CONNECTION_TOPIC=$CONNECTION_TOPIC \
     -e KAFKA_MESSAGES_DEFAULT_TOPIC=$KAFKA_MESSAGES_DEFAULT_TOPIC \
     -e KAFKA_MESSAGES_TOPICS_PATTERNS=$KAFKA_MESSAGES_TOPICS_PATTERNS \
     -e KAFKA_STREAMS_APPLICATION_NAME=$KAFKA_STREAMS_APPLICATION_NAME \
     -e KAFKA_STREAMS_STATE_DIRECTORY=$KAFKA_STREAMS_STATE_DIRECTORY \
     -e KAFKA_RESET_STREAMS_ON_START=$KAFKA_RESET_STREAMS_ON_START \
     -e KAFKA_RESET_STREAMS_ON_EXIT=$KAFKA_RESET_STREAMS_ON_EXIT \
     -e CENTRALIZED_CONSUMER_LISTENER_QUEUE=$CENTRALIZED_CONSUMER_LISTENER_QUEUE \
     -e MQTT_BLOCKING_THREAD_POOL_SIZE=$MQTT_BLOCKING_THREAD_POOL_SIZE \
     -e MAX_QUEUED_INCOMMING_MESSAGES=$MAX_QUEUED_INCOMMING_MESSAGES \
     -e MQTT_MAX_IN_FLIGHT_MESSAGES=$MQTT_MAX_IN_FLIGHT_MESSAGES \
     -e MONITORING_INCLUDE_JAVA_METRICS=$MONITORING_INCLUDE_JAVA_METRICS \
     -e MQTT_MAX_MESSAGE_SIZE=$MQTT_MAX_MESSAGE_SIZE \
     -e WATERSTREAM_JAVA_OPTS="-Xmx$WATERSTREAM_MAX_HEAP -Xmx$WATERSTREAM_MAX_HEAP" \
     -v $SCRIPT_DIR/waterstream.license:/etc/waterstream.license:ro \
     -p $MQTT_PORT:1883 \
     -p $MONITORING_PORT:1884 \
     --name $CONTAINER_NAME $IMAGE_NAME

#     -e KAFKA_BATCH_SIZE=210000 \

#TODO define this variable only when max heap is specified and non-empty
#     -e WATERSTREAM_JAVA_OPTS="-Xmx$WATERSTREAM_MAX_HEAP -Xmx$WATERSTREAM_MAX_HEAP" \


